name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check"
        run: cargo check --all
      - name: "Build"
        run: cargo build --all
      - name: "Test"
        run: cargo test --all
      - uses: docker-practice/actions-setup-docker@master
      - name: "Test Setup"
        run: |
          .github/setup.sh
          ./bin/dora-coordinator run .github/test-dataflow.yml

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Clippy"
        run: cargo clippy --all

  rustfmt:
    name: "Formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "rustfmt"
        run: cargo fmt --all -- --check

    # name: "License Checks"
    # runs-on: ubuntu-latest
    # steps:
      # - uses: actions/checkout@v2
      # - run: cargo install cargo-lichking
      # - name: "Check dependency licenses"
        # run: cargo lichking check
